//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.17 at 02:00:16 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/xml/employer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.xml.employer;
